ORG 0000H
LJMP MAIN // TO SURPASS THE INTERRUPT VECTOR TABLE
ORG 001BH // TIMER 1 ISR
CPL P1.1 // TOGGLE P1.1 FOR GENERATING 7KHZ SQUAREWAVEFORM
RETI // RETURN FROM ISR
ORG 000BH // TIMER 0 ISR
CPL P1.0 // TOGGLE P1.0 FOR GENERATING 500HZ SQUAREWAVEFORM
CLR TF0 // CLEARING TIMER FLAG
MOV TH0,#0FCH // TIMER 0 - HIGHER BYTE
MOV TL0,#066H // TIMER 0 - LOWER BYTE
SETB TR0 // STARTING TIMER 0
RETI // RETURN FROM ISR
ORG 0100H // MAIN PROGRAM
MAIN:MOV IE,#08AH // ENABLING INTERRUPT FOR TIMER 0 AND TIMER 1 IE = 1000 1010
MOV TMOD,#21H // TIMER 1 IN MODE 2, TIMER 0 IN MODE 1
MOV TH1,#-66 // SETTING TH1 = -66
MOV TL0,#066H // TIMER 0 - LOWER BYTE
MOV TH0,#0FCH // TIMER 0 - HIGHER BYTE
SETB TR0 // START TIMER 0
SETB TR1 // START TIMER 1
HERE: SJMP HERE
END
