ORG 0000H
MOV TMOD,#21H //TIMER 1 MODE2 AND TIMER 0 FOR WAVE
MOV TH1,#-3 //BAUD RATE 9600
MOV SCON,#50H //8-BIT 1 STOP,REN ENABLED
CLR P2.1 //SQUARE WAVE PORT
MOV P0,#0 //COPYING VALUE 0 TO P0RT 0
SETB TR1 //START TIMER 1
HERE:JNB RI,HERE
MOV A,SBUF //SAVE RECEIVED DATA TO A
MOV P0,A //MOVING RECEIVED DATA TO P0
CJNE A,#"1",SWG_2 //JUMP IF A NOT EQUAL TO 1
MOV TL0,#33H //TLO=33H THE LOW BYTE FOR 1KHZ
MOV TH0,#0FEH //THO=FEH THE HIGH BYTE FOR 1KHZ
SETB TR0 //START TIMER 0
LOOP_1:JNB TF0,LOOP_1 //JUMP CALL FOR LOOP1
CPL P2.1 //TOGGLE P2.1
CLR TR0 //STOP TIMER 0
CLR TF0 //STOP FLAG 0
SWG_2:CJNE A,#"2",SWG_3 //JUMP IF A NOT EQUAL TO 2
MOV TL0,#1AH //TLO=1AH THE LOW BYTE FOR 2KHZ
MOV TH0,#0FFH //THO=FFH THE HIGH BYTE FOR 2KHZ
SETB TR0 //START TIMER 0
LOOP_2:JNB TF0,LOOP_2 //JUMP CALL FOR LOOP2
CPL P2.1 //TOGGLE P2.1
CLR TR0 //STOP TIMER 0
CLR TF0 //STOP FLAG 0
SWG_3:CJNE A,#"3",SWG_4 //JUMP IF A NOT EQUAL TO 3
MOV TL0,#66H //TLO=1AH THE LOW BYTE FOR 2KHZ
MOV TH0,#0FFH //THO=FFH THE HIGH BYTE FOR 2KHZ
SETB TR0 //START TIMER 0
LOOP_3:JNB TF0,LOOP_3 //JUMP CALL FOR LOOP3
CPL P2.1 //TOGGLE P2.1
CLR TR0 //STOP TIMER 0
CLR TF0 //STOP FLAG 0
SJMP HERE //SHORT JUMP
SWG_4:
SJMP HERE
END
